- t/123-lua-path.t
In my nginx implementation only explicitly set envs are visible.
Other strategy is to handle this is to add these at Test::Nginx::Util write_config_file lines 814-815.
> fix env tests

- README.markdown
> doc fix: ngx.exit is not disabled within header_filter_by_lua

- src/ngx_http_lua_req_body.c
- src/ngx_http_lua_shdict.c
checked by ngx-style: https://github.com/openresty/nginx-devel-utils/pull/6
> style fix: variable name align with the previous line

- README.markdown
- doc/HttpLuaModule.wiki
According to #254 and commit e549fc2df0c03648a4553c8310c90c61db46aa42 log_by_lua runs before classic nginx access logs. This was missed in the docs.
> doc: fix log_by_lua, runs before nginx access log and after

- README.markdown
Was playing with `sock:receive` and realised the sample code was outputting the wrong variable.
> Small documentation fix to sample code

- README.markdown
- doc/HttpLuaModule.wiki
Was just browsing code and docs when I noticed it was missing too :o
> docs: add get_phase() result in "balancer" context

- README.markdown
The sample with incorrect ending of if block will cause 500 error.
> Fix conf sample syntax error in README

- src/ngx_http_lua_util.c
- t/001-set.t
- t/158-global-var.t
* more appropriate message ("writing" instead of "attempting to")
* remove http/lua prefix (`ngx.log` will inject `[lua]` and `stream [lua]`
already)
* remove unused cached global
* cache `tostring` global locally
> misc: updated _G write guard message to be more accurate.

- README.markdown
- doc/HttpLuaModule.wiki
This ports changes from 5efd95d793bad0587f75a7d0f701b76693c1311d to the
HttpLuaModule.wiki file, with a few minor edits. The wiki2markdown.pl
script was also run, and caught a few leftovers in the README.markdown
file.
> doc: ported the Lua 5.1 interpreter removal to the wiki document.

- src/ngx_http_lua_common.h
In WIN64, the pointer type is 64 bits but the long type is 32 bits.
Since WIN64 only supports x64 and IA64, we could confirm that it doesn't
need the mask.
If we need the mask in the future, we might need to use a C compiler
which supports C99 (like MSVC 2013+ or any other modern C compiler) to build
the WIN64 version.
> bugfix: the lightuserdata mask was broken in WIN64.

- t/004-require.t
Those regexes used to not play nice with existing `LUA_PATH` and `LUA_CPATH` environment variables, especially empty path segments `;;` (which can happen anywhere in those paths) or in cases where those variables are empty (in which case `;;` is left unchanged from the specified `lua_package_*path`). We also made the regexes slightly more robust in other subtle ways.
> tests: require: hardened lua_path and lua_cpath regexes.

- src/ngx_http_lua_common.h
- src/ngx_http_lua_headers.c
- src/ngx_http_lua_headers_out.c
- src/ngx_http_lua_headers_out.h
- src/ngx_http_lua_subrequest.c
- src/ngx_http_lua_util.c
- src/ngx_http_lua_util.h
- t/016-resp-header.t
> bugfix: generated defualt Content-Type header when Content-Type header is not set

- src/ngx_http_lua_module.c
- t/160-disable-init-by-lua.t
Previously, when Nginx is run as a signaller like `nginx -p . -s stop`, the code in `init_by_lua*` will be executed. Now this probably unexpected behavior is avoided.
> change: avoided running any init_by_lua* code inside signaller process and when testing Nginx configuration.

- src/ngx_http_lua_timer.c
Previously no error will be logged when there is not resource to run an
expired timer.
> feature: logged error when failed to run timer.

- README.markdown
- doc/HttpLuaModule.wiki
- src/ngx_http_lua_socket_tcp.c
- src/ngx_http_lua_socket_tcp.h
- t/068-socket-keepalive.t
Now we could pass 'pool_size' and 'backlog' options in connect method to
specify the pool size and the queue size of connection pool.
When there is more connect operations than the pool_size, new connect
operation will be queued until former connect operation fails or
connection finalizes.
When there is more queueing connect operations than the backlog, new
connect operation will be dropped.
This pr also migrated connection pool creation to connect method.
Note that the meaning of `active_connections` is changed from the previous
setkeepalive mechanism. The connection pool is destroyed only if all related
connections closed now.
The implementation of tcp cosocket is quite complex, therefore both strict
code review and extreme testing are required before merging this feature into
master.
I …
> feature: added queue to connection pool

- t/159-sa-restart.t
The handler for this signal falls-through to a graceful shutdown in
daemonized worker processes.
> tests: 159-sa-restart.t: avoided sending SIGWINCH to the test nginx worker process.

- .travis.yml
- README.markdown
- doc/HttpLuaModule.wiki
- src/api/ngx_http_lua_api.h
lua-resty-core PR: https://github.com/openresty/lua-resty-core/pull/237
> api: bumped API version to 0.10.15.

- t/000--init.t
> tests: removed no-longer needed drizzle upstream block in init.t.

- t/129-ssl-socket.t
> tests: ssl-socket.t: fixed a failing test case due to openresty.org's default cipher.

- README.markdown
- doc/HttpLuaModule.wiki
This is just a really trivial doc change :-)
Originally I wanted to change the documentation of `tcpsocket:receiveany()` to specify that *some* data is always returned, even if none was available at the time the call is made. (Right?) But I punted on that because maybe this is supposed to be implied when saying that the call is *synchronous.* (It wasn't obvious to me so I had to peek at the C code fwiw.)
The one-liner is what was then left on that branch :grin: 
----
> doc: fix thinko in tcpsocket:receiveany()

- .travis.yml
- README.markdown
- doc/HttpLuaModule.wiki
- src/ngx_http_lua_module.c
- src/ngx_http_lua_ssl_session_fetchby.c
- src/ngx_http_lua_ssl_session_fetchby.h
> feature: supported async SSL session fetch callback with OpenSSL 1.1.1.

- config
Follow-up commit to 2014dd80fe4f299ad68c3b60a2c5f846b4286b6f
> bugfix: ensured the 'pcre_version' symbol is also preserved on Darwin platforms.

- src/ddebug.h
- src/ngx_http_lua_clfactory.c
- src/ngx_http_lua_common.h
- src/ngx_http_lua_log_ringbuf.c
- src/ngx_http_lua_logby.h
- src/ngx_http_lua_module.c
- src/ngx_http_lua_pipe.c
- src/ngx_http_lua_regex.c
- src/ngx_http_lua_shdict.c
- src/ngx_http_lua_socket_tcp.c
- src/ngx_http_lua_util.c
This is a sister PR of https://github.com/openresty/meta-lua-nginx-module/pull/71. It ports changes made to the ngx_meta_lua module into this module.
> chore: ngx_meta_lua alignment and inherited fixes

- src/ngx_http_lua_common.h
- src/ngx_http_lua_coroutine.c
- src/ngx_http_lua_util.c
- t/062-count.t
- t/091-coroutine.t
The manual states that [coroutine.wrap](https://github.com/openresty/lua-nginx-module#coroutinewrap) is "Similar to the standard Lua API". However, the Lua API's `coroutine.wrap` has some nuances compared to the one provided by ngx_lua:
> Returns the same values returned by resume, except the first boolean. In case of error, propagates the error.
[Source (Lua 5.1 manual)](https://www.lua.org/manual/5.1/manual.html#pdf-coroutine.wrap).
This caused me some issues in the daily job's latest release, where we expected errors encountered in `coroutine.wrap` to be propagated to the Lua main thread, and cause 500 errors. But those errors were swallowed by the thread "scheduler". …
> bugfix: coroutine.wrap: propagate errors to the parent coroutine.

- src/ngx_http_lua_directive.c
- src/ngx_http_lua_directive.h
- src/ngx_http_lua_module.c
Similarly as other directives and options (e.g. our patch to support `resolver ... ipv6=...` on builds without IPv6 support), `lua_regex_cache_max_entries` and `lua_regex_match_limit` are now supported when NGINX is built without PCRE support. The directives are simply ignored.
Concretely, this allows for `resty` to be used even when NGINX lacks PCRE support, since [it hard-codes the lua_regex_cache_max_entries directive](https://github.com/openresty/resty-cli/blob/master/bin/resty#L734).
When users attempt to use PCRE APIs (e.g. `ngx.re`), lua-resty-core already produces friendly errors describing the lack of support for PCRE in the current NGINX build since recently.
Sister PR:
- https://github.com/openresty/lua-resty-core/pull/270
No tests for this change at the moment, as our test …
> feature: we now ignore 'lua_regex_*' directives when NGINX is compiled without PCRE support.

- src/ngx_http_lua_directive.c
- t/129-ssl-socket.t
Caught by Valgrind:
==1136586== Use of uninitialised value of size 8
==1136586==    at 0x48B3C55: lj_tab_getinth (lj_tab.c:411)
==1136586==    by 0x48CBC42: lua_rawgeti (lj_api.c:823)
==1136586==    by 0x5823D6: ngx_http_lua_cache_load_code (ngx_http_lua_cache.c:84)
==1136586==    by 0x5829F3: ngx_http_lua_cache_loadfile (ngx_http_lua_cache.c:286)
==1136586==    by 0x576A9E: ngx_http_lua_filter_set_by_lua_file (ngx_http_lua_directive.c:457)
==1136586==    by 0x549361: ndk_set_var_multi_value_data_code (ndk_set_var.c:215)
==1136586==    by 0x4FA637: ngx_http_rewrite_handler (ngx_http_rewrite_module.c:180)
==1136586==    by 0x481491: ngx_http_core_rewrite_phase (ngx_http_core_module.c:922)
==1136586==    by 0x4812ED: ngx_http_core_run_phases (ngx_http_core_module.c:868)
==1136586==    by …
> bugfix: fixed use of an uninitialized value in ngx_http_lua_set_by_lua_file.

- doc/HttpLuaModule.wiki
> doc(ngx.sleep): fix grammar typo

- src/ngx_http_lua_directive.c
Caught by running the 025-codecache.t test suite in HUP reload mode.
> bugfix: fixed use of uninitialized cache_key in ngx_http_set_by_lua_file.

- README.markdown
- doc/HttpLuaModule.wiki
- src/ngx_http_lua_control.c
- src/ngx_http_lua_headers_in.c
- src/ngx_http_lua_headers_out.c
- src/ngx_http_lua_uri.c
- src/ngx_http_lua_util.c
- src/ngx_http_lua_util.h
- t/016-resp-header.t
- t/022-redirect.t
- t/028-req-header.t
- t/030-uri-args.t
- t/113-req-header-cookie.t
> bugfix: ensured arguments of APIs mutating uri or request/response headers do not contain unsafe characters.

- src/ngx_http_lua_headers.c
When multiple values are associated to the header, we should override
the header only for the first time, otherwise the following value will
override the previous one.
> bugfix: overrided the input header only for the first time

- README.markdown
- doc/HttpLuaModule.wiki
---
Before the fix:
* `doc/HttpLuaModule.wiki` rendered to HTML using MediaWiki API: [link](https://tinystash.undef.im/il/4wSigPZTMqZcXxT8gGH8PeHBaza8zpNskT9UY7zWDmDTmH9Gyx8bogjyt2zei9ApFqAAkDEFJz4oaoDVQ91Ztswc.html#ngx.escape_uri)
* `README.markdown` rendered by GitHub, screenshot: ![image](https://user-images.githubusercontent.com/2131407/86520057-7bf89480-be49-11ea-8d8c-ba540a952704.png)
> doc: fix unclosed <code> tag breaking markup

- src/ngx_http_lua_coroutine.c
- src/ngx_http_lua_pipe.c
- src/ngx_http_lua_semaphore.c
- src/ngx_http_lua_sleep.c
- src/ngx_http_lua_socket_tcp.c
- src/ngx_http_lua_socket_udp.c
- src/ngx_http_lua_uthread.c
- src/ngx_http_lua_util.h
> refactor: used 'yieldable context' to simpify the context list.

- README.markdown
- doc/HttpLuaModule.wiki
- src/ngx_http_lua_socket_tcp.c
- t/062-count.t
- t/067-req-socket.t
- t/116-raw-req-socket.t
> Support receiveany on ngx.req.socket(true?) socks

- src/ngx_http_lua_util.h
The bracket is missing in the previous refactor.
> bugfix: macro contains operator should be wrapped inside a bracket.

- src/ngx_http_lua_args.c
- src/ngx_http_lua_directive.c
- src/ngx_http_lua_headers.c
- src/ngx_http_lua_headers_in.c
- src/ngx_http_lua_initworkerby.c
- src/ngx_http_lua_log.c
- src/ngx_http_lua_req_body.c
- src/ngx_http_lua_socket_tcp.c
- src/ngx_http_lua_string.c
- src/ngx_http_lua_util.c
> style: added blank lines after code block.

- src/ngx_http_lua_ssl_certby.c
- t/140-ssl-c-api.t
This PR adds a FFI interface that allows users to configure SSL client certificate verification dynamically. For example, Nginx can now read SNI first and then determine whether to request a client certificate during handshake. Optionally, caller can pass in a CA list used for verification.
> feature: add FFI interface to verify SSL client certificate

- README.markdown
- doc/HttpLuaModule.wiki
as per subject, correct the phase info for `lua_need_request_body`. I assume this should be rewrite/access/**content**_by_lua
> Update/correct phase info for lua_need_request_body

- README.markdown
- doc/HttpLuaModule.wiki
@doujiang24 @thibaultcha 
https://github.com/openresty/lua-nginx-module/pull/1757#issuecomment-668156744
> doc: removed the useless semicolon in the example lua code

- src/ngx_http_lua_socket_tcp.c
variable size overflow when reading data larger than 4GB under 32-bit operating system
see: https://forum.openresty.us/d/6408-324g
> bugfix: type size_t overflow under 32-bit operating system

- src/ngx_http_lua_socket_tcp.c
- t/023-rewrite/unix-socket.t
- t/058-tcp-socket.t
- t/059-unix-socket.t
- t/068-socket-keepalive.t
In [ngx.socket.tcp:connect](https://github.com/openresty/lua-nginx-module#ngxsocketconnect), if host is a TCP socket, the third parameter could be `nil`, it is to some third part module to write their code like this:
```
function _M.connect(host, port, opt)
sock = ngx.socket.tcp()
sock:connect(host, port, opt)
end
```
But if the host is a unix-domain socket, the second parameter could not be a `nil`, we have to write the code like this:
```
function _M.connect(path, opt)
sock = ngx.socket.tcp()
if opt ~= nil then
sock:connect("unix:" .. path, opt)
else
sock:connect("unix:" .. path)
end
end
```
Just like here: https://github.com/openresty/lua-resty-redis/pull/200/files#diff-adb515948c05651051c83fd6fb3ce7ceR143-R149. I think it is a comment use way, so update the second parameter and allow …
> feature(socket.tcp): enhance the logic of parameter verification in

- src/ngx_http_lua_balancer.c
- t/138-balancer.t
if they exist.
This bug was discovered first by Kong users in
https://github.com/Kong/kong/issues/6212. After investigation, it seems
that the cause is that when calling `create_request` function
multiple times, it may incorrectly consider the buffer created in the
last call request body data, causing both the old and new request buffer
to be sent to the upstream.
This PR checks the request buffer chain link before calling the
`create_request` function. If it contains a buffer generated previously,
that buffer is skipped first so the new buffer that will be generated
falls in at the correct location.
This bug only affects user calling the new `recreate_request` API during balancer retries, for users not calling it they are not impacted.
I hereby granted the copyright of the changes in …
> bugfix: when recreating balancer buffer, remove existing buffers first

- src/ngx_http_lua_socket_tcp.c
lua_pushfstring() doesn't accept '%i' format. We should use '%d'
instead.
> fix format in argerror messages

- src/ngx_http_lua_module.c
`ngx_http_lua_module_ctx` is none public, and almost other modules in official release all mark `ngx_module_t.ctx` variable static.
> style: mark private ngx_http_lua_module_ctx static

- t/089-phase.t
- t/154-semaphore.t
- t/162-exit-worker.t
- t/163-exit-worker-hup.t
> tests: --- shutdown_error_log should be excluded from repeat_each() when counting plans.

- src/ngx_http_lua_socket_tcp.c
> bugfix: fixed segfault caused by an incorrect format token introduced in commit 3e24a95a.

- src/ngx_http_lua_headers_in.c
- src/ngx_http_lua_headers_out.c
> bugfix: ngx.resp.set_headers(): may cause an error when Content-Length field is larger than 2^32.

- src/ngx_http_lua_headers.c
> bugfix: accessed memory out of range when calling lua_pushfstring with none zero-terminated string introduced in commit 7367a231.

- src/ngx_http_lua_common.h
- src/ngx_http_lua_coroutine.c
- src/ngx_http_lua_util.c
- src/ngx_http_lua_util.h
This function can be very expensive when there are a lot of zombie
threads in the current context.
> optimize: post zombie thread: avoided the linear search.

- README.markdown
- doc/HttpLuaModule.wiki
- src/api/ngx_http_lua_api.h
> bumped the API version to 0.10.19.

- src/ngx_http_lua_pipe.c
> bugfix: we closed listener's fd which was closed.

- src/ngx_http_lua_logby.c
If turn on nginx debug log `./configure --with-debug ...`, but not select `debug_http` log level. 
ngx_log_debug1(NGX_LOG_DEBUG_HTTP, ...) will be ignored, malloc_trim() can't be executed as function parameter.
And memory isn't returned to OS immediately. This bug may cause serious memory leak, OOM.
Simply,  `ngx_log_debug1` is optional, but `malloc_trim` obligatory. 
> bugfix: memory leak of debug log

- src/ngx_http_lua_ssl_certby.c
```
deref_ptr: Directly dereferencing pointer c.
419    if (c->addr_text.len) {
420        p = ngx_snprintf(buf, len, ", client: %V", &c->addr_text);
421        len -= p - buf;
422        buf = p;
423    }
424
CID 149837 (#1 of 1): Dereference before null check (REVERSE_INULL)check_after_deref: Null-checking c suggests that it may be null, but it has already been dereferenced on all paths leading to the check.
425    if (c && c->listening && c->listening->addr_text.len) {
426        p = ngx_snprintf(buf, len, ", server: %V", &c->listening->addr_text);
427        /* len -= p - buf; */
428        buf = p;
429    }
```
> src/ngx_http_lua_ssl_certby.c: fix possible null pointer dereference found by coverity

- src/ngx_http_lua_ssl_session_storeby.c
```
329    c = log->data;
330
deref_ptr: Directly dereferencing pointer c.
331    if (c->addr_text.len) {
332        p = ngx_snprintf(buf, len, ", client: %V", &c->addr_text);
333        len -= p - buf;
334        buf = p;
335    }
336
CID 251578 (#1 of 1): Dereference before null check (REVERSE_INULL)check_after_deref: Null-checking c suggests that it may be null, but it has already been dereferenced on all paths leading to the check.
337    if (c && c->listening && c->listening->addr_text.len) {
338        p = ngx_snprintf(buf, len, ", server: %V", &c->listening->addr_text);
339        buf = p;
340    }
341
```
> chore: fix possible null pointer dereference found by Coverity

- t/162-exit-worker.t
> tests: fixed typo in 162-exit-worker.t.

- README.markdown
- src/ngx_http_lua_util.c
- t/006-escape.t
test case like: "%20%1a%a1%au%ua"
Original implementation fails to handle invalid quote sequence correctly:
1. '%'s are discarded, which are preserved by most implementation;
2. when the problem happens at last charactor(and string is not null-terminated), an extra charactor will be copied
> bugfix: correct the way to handle invalid quote in ngx.escape_uri/ngx.req.get_{uri,post}_args

- README.markdown
- doc/HttpLuaModule.wiki
We have broken doc/HttpLuaModule.wiki since https://github.com/openresty/lua-nginx-module/commit/eb944dedd28231a99d8a2a71cbc392ce2dad36c1
> doc: sync doc from README to ensure wiki2markdown.pl is work

- src/ngx_http_lua_timer.c
- src/ngx_http_lua_util.c
stripped the trailing whitespaces introduced in commit ad2b404d.
> doc: stripped line trailing whitespaces.

- src/ngx_http_lua_ssl_certby.c
> feature: allow to be compiled with LibreSSL 3.0+

- src/ngx_http_lua_ssl_certby.c
It leads to 'error: ‘ngx_http_lua_ssl_verify_callback’ defined but not used [-Werror=unused-function]'
error.
> bugfix: we didn't exclude the ssl_verify_callback when compiling with LibreSSL

- .travis.yml
> travis-ci: remove clang compiler mode from travis.

- README.markdown
- doc/HttpLuaModule.wiki
- src/ngx_http_lua_timer.c
- t/162-exit-worker.t
Since nginx has been confirmed that all timers have been cleaned up when exit worker is executed, all timers will no longer be executed in exit worker phase. 
Reference https://github.com/nginx/nginx/blob/f02e2a734ef472f0dcf83ab2e8ce96d1acead8a5/src/os/unix/ngx_process_cycle.c#L715
> chore: check context in ngx.timer.* for exit process

- .travis.yml
- src/ngx_http_lua_bodyfilterby.c
- src/ngx_http_lua_common.h
- src/ngx_http_lua_output.c
- t/082-body-filter-2.t
> bugfix: buffer bloat and CPU 100% when download large file was filtered by body_filter_by_lua.

- .travis.yml
- src/ngx_http_lua_bodyfilterby.c
- src/ngx_http_lua_module.c
- src/ngx_http_lua_pipe.c
- src/ngx_http_lua_ssl_session_fetchby.c
- src/ngx_http_lua_ssl_session_storeby.c
- src/ngx_http_lua_util.c
- src/ngx_http_lua_worker_thread.c
> style: fixed some of the code style issues and add style check for ci.

- src/ngx_http_lua_regex.c
- t/120-re-find.t
lua_regex_match_limit takes effect globally for all regexes used in ngx.re
api. However, the match_limit field of pcre_extra block is not supported in
pcre_dfa_exec()(so does match_limit_recursion), because it is meaningless
in DFA matching. And pcre_dfa_exec() will return -18(PCRE_ERROR_DFA_UMLIMIT)
when the directive is used. Here we just ignore the directive in DFA mode.
> bugfix: we should ignore match limit in DFA mode.

- src/ngx_http_lua_util.c
since we already changed to create the table from Lua in resty.core.ctx.
related change:
https://github.com/openresty/lua-resty-core/commit/2d667ec81497a7a2ec10bd6b7d1f27509637c928
> change: do not need to create the Lua request ctx data table from C

- src/ngx_http_lua_shdict.c
- t/145-shdict-list.t
修复一个share dict list过期处理的问题：
当向一个过期的list push时，
如果过期的list没有被清除，重新复用时，list长度没有重新置为0，导致新队列pop时，返回500
例子：
local dogs = ngx.shared.dogs
dogs:lpush("cc", "1")
dogs:lpush("aa", "1")
dogs:expire("aa", 0.2)
ngx.sleep(0.3)
dogs:lpush("aa", "2")
dogs:lpop("aa")
dogs:lpop("aa")     --此时触发500，而不是期望的返回nil
> bugfix:fix expired(not cleared)share dict list len incorrect problem

- .travis.yml
> tests: travis failed due to cetificate of Let's Encrypt expired.

- src/ngx_http_lua_timer.c
fix #1941.
```
** CID 339181:  Null pointer dereferences  (REVERSE_INULL)
/src/ngx_http_lua_timer.c: 326 in ngx_http_lua_ngx_timer_helper()
________________________________________________________________________________________________________
*** CID 339181:  Null pointer dereferences  (REVERSE_INULL)
/src/ngx_http_lua_timer.c: 326 in ngx_http_lua_ngx_timer_helper()
320
321         } else {
322             tctx->client_addr_text.len = 0;
323             tctx->client_addr_text.data = NULL;
324         }
325
>>>     CID 339181:  Null pointer dereferences  (REVERSE_INULL)
>>>     Null-checking "ctx" suggests that it may be null, but it has already been dereferenced on all paths leading to the check.
326         if (ctx && ctx->vm_state) {
327             tctx->vm_state = ctx->vm_state;
328 …
```
> chore: fix possible null pointer dereference found by Coverity.

- t/157-socket-keepalive-hup.t
> tests: wrong pid path when running jobs greater than 1.

- t/082-body-filter-2.t
- t/166-worker-thread.t
* skip test cases for t/082-body-filter-2.t when the event type is not
'poll'.
* skip test cases for t/166-worker-thread.t when the event do not support
worker thread.
> tests: skip test cases for unsupported event types.

- src/ngx_http_lua_exitworkerby.c
- src/ngx_http_lua_worker_thread.c
- src/ngx_http_lua_worker_thread.h
> bugfix: forgot to clean cached thread contexts when worker process exit.

- t/132-lua-blocks.t
- t/158-global-var.t
> tests: 132-lua-blocks.t and 158-global-var.t: use RegExp instead of strict character match.

- src/ngx_http_lua_util.c
found by core dump caused by running TEST 3 of t/072-conditional-get.t in
mockeagain write mode.
> bugfix: prevent illegal memory access in ngx_http_lua_util.c.

- src/ngx_http_lua_headers.c
- t/016-resp-header.t
the original PR is https://github.com/openresty/lua-nginx-module/pull/1384.
the ngx.header was rewrite via ffi. So need to rewrite this feature.
> feature: expose the 'Last-Modified' response header as ngx.header["Last-Modified"].

- .travis.yml
> tests: fixed ngx-releng missing ack dependency.

- src/ngx_http_lua_common.h
- src/ngx_http_lua_directive.c
- t/002-content.t
> bugfix: the error message should use the first line rather than the last line of the code block when load lua code block failed.

- README.markdown
We now have `exit_worker_by_lua`, so we should remove this item.
> doc: update readme todo

- README.markdown
- doc/HttpLuaModule.wiki
--
Without using the `ssl_session*` API, this change will avoid misunderstandings if someone wants to build this module manually with another SSL library.
Close #2020
> doc: modify openssl patch requirements.

- src/ngx_http_lua_socket_tcp.c
```
*** CID 352757:  Null pointer dereferences  (FORWARD_NULL)
/src/ngx_http_lua_socket_tcp.c: 1733 in
ngx_http_lua_ffi_socket_tcp_sslhandshake()
1727     #else
1728             *errmsg = "no OCSP support";
1729             return NGX_ERROR;
1730     #endif
1731         }
1732
>>>     CID 352757:  Null pointer dereferences  (FORWARD_NULL)
>>>     Dereferencing null pointer "server_name".
1733         if (server_name->len == 0) {
1734             u->ssl_name.len = 0;
1735
1736         } else {
1737             if (u->ssl_name.data) {
1738                 /* buffer already allocated */
```
> fix potential null pointer dereference found by Coverity

- src/ngx_http_lua_timer.c
> bugfix: wrong memory size for the pernding timers array.

- src/ngx_http_lua_pipe.c
> optimize: add error log when closing the pipe failed.

- src/ngx_http_lua_headers_in.c
- src/ngx_http_lua_headers_out.c
This fixes [nginx 1.23.0 and ngx_http_lua_headers_in.c cookies -> cookie · Issue #2062 · openresty/lua-nginx-module](https://github.com/openresty/lua-nginx-module/issues/2062)
> Update handling of multiple headers changed in nginx 1.23.0

- README.markdown
Consider the following example:
```lua
local function print_tm()
print("Running: ", ngx.timer.running_count(), " Pending: ", ngx.timer.pending_count())
end
print("init")
print_tm()
local function spawn()
local t1 = ngx.thread.spawn(function()
ngx.sleep(5)
print("t1 done")
return "t1"
end)
local t2 = ngx.thread.spawn(function()
ngx.sleep(1)
print("t2 done")
return "t2"
end)
local wait = function()
local w = ngx.thread.wait(t1, t2)
print("wait returned: ", w)
end
print("before spawn")
print_tm()
return wait
end
ngx.timer.at(0, function()
spawn()()
print("exit")
end)
print("after timer.at")
print_tm()
while true do
print_tm()
ngx.sleep(1)
end
```
The timer's callback functions …
> doc: add detail on explanation of a running timer

- src/ngx_http_lua_pipe.c
We found that after running for a while, signalfd does not receive notifications.
> bugfix: add a timed recycling child process as a last resort.

- src/ngx_http_lua_socket_tcp.c
In this PR https://github.com/openresty/lua-nginx-module/pull/2136, I forgot to use forward declaration to declare a new variable. This PR has refactored the declaration style and fixed some type cast.
> style: use forward declaration for variable.

- src/ngx_http_lua_pipe.c
> bugfix: cleanup of http request will not be callled for the request created by ngx_http_lua_create_fake_request.

- t/168-tcp-socket-bind.t
cross request cosocket can not be reuese after connect().
> tests: cross requests cosocket can only be use one time.

- config
This reverts commit 1fd1e83c80612998647ee7ea933d3fdb2e9d9d9b.
> Revert "bugfix: doesn't set flags for Darwin arm64. (#2071)"

- README.markdown
- src/ngx_http_lua_module.c
- t/025-codecache.t
- t/129-ssl-socket.t
- t/143-ssl-session-fetch.t
> change: lua-ssl-protocols: Disabled SSLv3 and enable TLSv1.3 by default.

- src/ngx_http_lua_socket_tcp.c
- t/066-socket-receiveuntil.t
Please see https://github.com/openresty/lua-nginx-module/issues/2131 for more details.
Through recovering bytes from compiled pattern, other read calls are able to read these pending bytes instead of the following data, which avoids generating unexpected result. More details could be seen in code and comment.
> bugfix: mixed recv api call causes unexpected result.

- src/ngx_http_lua_socket_tcp.c
* according to doc of tcpsock:bind, add missing checking context
> bugfix: add missing checking context in ngx_http_lua_socket_tcp_bind

- src/ngx_http_lua_common.h
pcre.h is a PCRE header and is not exposed by PCRE2 library causing compilation error as the header is not found.
Don't include pcre.h if nginx is compiled with PCRE2 support enabled.
Fixes: cb83e33e2657 ("feature: support pcre2")
> bugfix: don't include pcre.h with PCRE2 used

- README.markdown
This sentence was in the README twice, so this PR removes the extra. 
---
> docs: remove duplicated sentence

- src/ngx_http_lua_subrequest.c
- src/ngx_http_lua_subrequest.h
- src/ngx_http_lua_util.c
- t/020-subrequest.t
PR introduces two features for ngx.location.capture().header:
- case-insensitive lookups (same as ngx.header.HEADER or ngx.req.get_headers())
- keeps original case for header names
> bugfix: fixed #1612 subrequest's header must be case-insensitive.

- README.markdown
- src/ngx_http_lua_accessby.c
- src/ngx_http_lua_contentby.c
- src/ngx_http_lua_req_body.c
- t/023-rewrite/request_body.t
- t/024-access/request_body.t
- t/044-req-body.t
#2174 mentioned an issue where there is a chance of blocking the ngx.read_body API when using HTTP/2. As a result, #2174 disabled the _ngx.read_body_ API in HTTP/2. However, #2211 also suggested that perhaps we should not completely disable the _ngx.read_body_ API in HTTP/2, as many HTTP/2 requests could still benefit from this.
To address this, I attempted to define the minimum limitations for using ngx.read_body in HTTP/2. From what I understand, ngx.read_body is based on the Nginx core to handle the client's body, and the Nginx core typically reads the entire client body before calling the callback registered by the lua-nginx-module. There are two scenarios in which …
> changes: modify ngx.read_body api limitation in HTTP/2 and HTTP/3

- README.markdown
- doc/HttpLuaModule.wiki
- src/ngx_http_lua_req_body.c
- t/010-request_body.t
In some scenarios(WAF,  logging，for example), we only want to read the first n bytes of the HTTP body. However, the ngx.req.get_body_data() always returns all the data.  If the body size is large, the overhead of copying memory between the Lua VM and the Nginx worker will be even greater.
so i add this feature to resolve #2252 
```lua
-- return first 1024
ngx.req.get_body_data(1024)
-- return all
ngx.req.get_body_data()
```
> feature: get_body_data() return max bytes

- t/129-ssl-socket.t
> tests: t/129-ssl-socket.t: use the same IP to ensure that the ssl session can be reused.

- src/ngx_http_lua_socket_tcp.c
Can be reproduced in valgrind mode in t/129-ssl-socket.t:
==55579== 13 bytes in 1 blocks are definitely lost in loss record 3 of 19
==55579==    at 0x483A809: malloc (vg_replace_malloc.c:307)
==55579==    by 0x44F522: ngx_alloc (ngx_alloc.c:22)
==55579==    by 0x549DDD: ngx_http_lua_ffi_socket_tcp_sslhandshake (ngx_http_lua_socket_tcp.c:1828)
==55579==    by 0x4897FEA: lj_vm_ffi_call (in /opt/luajit21/lib/libluajit-5.1.so.2.1.1700206165)
==55579==    by 0x48F7980: lj_ccall_func (lj_ccall.c:1402)
==55579==    by 0x4910E74: lj_cf_ffi_meta___call (lib_ffi.c:230)
==55579==    by 0x4895B7D: lj_BC_FUNCC (in /opt/luajit21/lib/libluajit-5.1.so.2.1.1700206165)
==55579==    by 0x5360E6: ngx_http_lua_run_thread (ngx_http_lua_util.c:1184)
==55579==    by 0x54203E: …
> bugfix: fixed memory leak in the case of connection in dubious.

- src/ngx_http_lua_shdict.c
> change: don't move the item with expire time to the head when lookup.

- t/082-body-filter-2.t
> tests: 082-body-filter-2.t: skip this test if mockeagain is not loaded correctly.

- src/ngx_http_lua_ssl_certby.c
- t/140-ssl-c-api.t
> feature: add ngx_http_lua_ffi_ssl_client_random.

- src/ngx_http_lua_regex.c
Also update the name of `ovecsize` in `ngx_http_lua_ffi_exec_regex`  to reflect the difference.
> bugfix: correct offset vector memory allocation size for PCRE2.

- config
- src/ngx_http_lua_ssl_export_keying_material.c
- src/ngx_http_lua_ssl_export_keying_material.h
I hereby granted the copyright of the changes in this pull request to the authors of this lua-nginx-module project.
TLS has the support to derive key material from the TLS master secret that can be used on the application level. This is described in RFC8446 section 7-5. OpenSSL offers support for this [here](https://www.openssl.org/docs/man1.1.1/man3/SSL_export_keying_material.html).
We would like to use these functions from lua. This PR adds the required functions for that.
> Add suport for deriving key from tls master secret

- src/ngx_http_lua_ssl_ocsp.c
Required by https://github.com/openresty/lua-resty-core/pull/296
This is an alternative solution to https://github.com/openresty/lua-nginx-module/pull/1041. I like the approach in this PR better because it adds minimal amount of code and it makes sense for validation API to return this data.
The code has been [fork lifted from Nginx source](https://github.com/nginx/nginx/blob/3ba88365b5acef17f01671cd969c909dee5e2cde/src/event/ngx_event_openssl_stapling.c#L700) and adjusted here.
In addition to exposing `nextUpdate` field, this way we will also be validating `nextUpdate` field.
> validate and expose nextUpdate field in OCSP response

- src/ngx_http_lua_bodyfilterby.c
- t/082-body-filter-2.t
fix #2301
The reason is that when we set  `arg[1] = ""` first, the `lmcf->body_filter_chain` will be null
https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_bodyfilterby.c#L633-L646
https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_bodyfilterby.c#L668-L700
Then we can't set the right end flag
https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_bodyfilterby.c#L526-L549
> bugfix: the connection won't be closed normally when set arg[1] = "" before arg[2] = true

- config
Without the initialization, the feature test ends with:
```
error: 'set' may be used uninitialized [-Werror=maybe-uninitialized]
```
It is because of the [-Wmaybe-uninitialized](https://gcc.gnu.org/onlinedocs/gcc-11.1.0/gcc/Warning-Options.html#index-Wmaybe-uninitialized) enhancements in the gcc 11.
---
> bugfix: fix config test for signalfd with gcc 11

- src/ngx_http_lua_util.c
- t/002-content.t
Fix https://github.com/openresty/lua-nginx-module/issues/2320
> bugfix: fix lua-nginx-module context was clear when ngx.send_header() trigger filter_finalize case

- README.markdown
- doc/HttpLuaModule.wiki
- src/ngx_http_lua_balancer.c
- src/ngx_http_lua_balancer.h
- src/ngx_http_lua_common.h
- src/ngx_http_lua_module.c
Co-authored-by: Thibault Charbonnier <thibaultcha@me.com>
> feature: implemented keepalive pooling in 'balancer_by_lua*'. (#38)

- src/ngx_http_lua_balancer.c
```
lua-nginx-module/src/ngx_http_lua_balancer.c: In function ‘ngx_http_lua_balancer_get_peer’:
lua-nginx-module/src/ngx_http_lua_balancer.c:389:41: error: variable ‘u’ set but not used [-Werror=unused-but-set-variable]
389 |     ngx_http_upstream_t                *u;
|
```
> bugfix: fixed compilation errors when building without SSL.

- README.markdown
- src/ngx_http_lua_subrequest.c
- t/027-multi-capture.t
> feature: support ngx.location.capture and ngx.location.capture_multi with `headers` option

- src/ngx_http_lua_balancer.c
- t/188-balancer_keepalive_pool_max_retry.t
In the balancer phase, when obtaining a connection from the upstream connection pool, the `cached` attribute of the peer connection is set to 1(`pc->cached = 1;`), indicating that the connection is obtained from the cache.
If an error occurs during the use of this connection, such as "upstream prematurely closed connection" the system will increase the `tries` attribute of the peer connection by executing `u->peer.tries++`.
This PR restores tries by callbacks to the balancer when `u->peer.tries++` is unexpectedly set.
> bugfix: respect max retry after using balancer pool

- README.markdown
- doc/HttpLuaModule.wiki
- src/ngx_http_lua_balancer.c
- t/138-balancer.t
Context: https://github.com/openresty/lua-nginx-module/issues/2333
> bugfix: let `balancer.recreate_request` API work for body data changed case

- src/ngx_http_lua_shdict.c
> bugfix: treat shdict entries with ttl equal to 0 as expired.

- src/ngx_http_lua_balancer.c
fmt@entry=0x59c7f6 "bind(%V) failed", args=args@entry=0x7fff82779258) at src/core/ngx_string.c:255
> bugfix: nginx crashed when binding local address failed from lua.

- src/ngx_http_lua_socket_tcp.c
- t/129-ssl-socket.t
This bug was found in t/129-ssl-socket.t Test 18 when TEST_NGINX_EVENT_TYPE=poll enabled.
> bugfix: fixed keepalive error in cosocket.

- .travis.yml
- t/014-bugs.t
- t/020-subrequest.t
- t/068-socket-keepalive.t
- t/163-signal.t
- t/188-balancer_keepalive_pool_max_retry.t
> tests: bumped the NGINX core to 1.27.0.

- README.markdown
> doc: improve grammar

- src/ngx_http_lua_socket_tcp.c
- t/058-tcp-socket.t
When TLSv1.3 is used, the server may send a NewSessionTicket message after the handshake. While this message is ssl-layer data, `tcpsock:sslhandshake` does not consume it.
In the implementation of `setkeepalive`, `recv` is used to confirm the connection is still open and there is no unread data in the buffer. But it treats the NewSessionTicket message as application layer data and then `setkeepalive` fails with this error `connection in dubious state`.
In fact we don't need to peek here, because if the application data is read successfully then the connection is going to be closed anyway. Therefore, `c->recv` can be used instead which will consume the ssl-layer data implicitly.
A quick reproduction:
```
openssl s_server --debug -msg -port 11443 -cert server.crt -key server.key
```
```
$ …
```
> bugfix: `setkeepalive` failure on TLSv1.3

- .travis.yml
- t/129-ssl-socket.t
- t/140-ssl-c-api.t
- t/143-ssl-session-fetch.t
> tests: add support for openssl3.0.

- src/ngx_http_lua_misc.c
- t/015-status.t
> feature: add ngx.resp.set_status(status, reason).

- src/ngx_http_lua_misc.c
Without this patch I got:
```
> curl: (8) Nul byte in header
```
```lua
location = /bye {
content_by_lua_block {
local resp = require "ngx.resp"
resp.set_status(500, "custom status")
ngx.say("set_status_and_reason")
}
}
```
> bugfix: remove null terminator

- README.markdown
> documentation: Clarify base64url encoding and padding

- src/ngx_http_lua_socket_tcp.c
ngx_http_lua_socket_push_input_data will always succeed and therefore change its signature to void return type, it's unnecessary to do error check of it.
> bugfix: unnecessary to do error check

- src/ngx_http_lua_util.c
- t/014-bugs.t
I hereby granted the copyright of the changes in this pull request to the authors of this lua-nginx-module project.
releated: https://github.com/openresty/lua-nginx-module/issues/2397
refer: https://github.com/nginx/nginx/commit/d9887ee2ae9069843eed67d5b5ea625a7faeedb1
> feature: add function to bypass HTTP conditional request checks

- src/ngx_http_lua_bodyfilterby.c
> bugfix: ensure context is restorable when fd writable events

- src/ngx_http_lua_ssl_client_helloby.c
https://github.com/openresty/lua-resty-core/pull/498
> feature: ngx_http_lua_ffi_ssl_get_client_hello_ciphers()

- .travis.yml
- t/143-ssl-session-fetch.t
- util/build-with-dd.sh
- util/build-without-ssl.sh
- util/build.sh
> tests: bumped openssl to v3.4.1

- .travis.yml
- src/ngx_http_lua_ssl_certby.c
- src/ngx_http_lua_ssl_client_helloby.c
- src/ngx_http_lua_util.c
- src/ngx_http_lua_util.h
- t/139-ssl-cert-by.t
- t/143-ssl-session-fetch.t
- t/166-ssl-client-hello.t
https://github.com/openresty/openresty/pull/1063
https://github.com/openresty/openresty-devel-utils/pull/58
When using HTTP/3, yield Lua APIs (such as ngx.sleep, cosocket, ngx.thread.*, etc.) in ssl_certificate_by_lua* and ssl_client_hello_by_lua* directives cannot work properly, causing HTTP/3 request connections to be abnormally disconnected.
HTTP/3 in nginx is implemented through QUIC code, and its SSL handling mechanism is significantly different from traditional HTTP/1.x and HTTP/2. 
Currently, nginx QUIC SSL has three implementation approaches:
1. OpenSSL traditional interface compatibility mode (target of this fix)
2. BoringSSL implementation
3. OpenSSL 3.5+ official …
> bugfix: improve HTTP/3 SSL Lua callback yield handling

- README.markdown
- doc/HttpLuaModule.wiki
- src/ngx_http_lua_common.h
- src/ngx_http_lua_module.c
- src/ngx_http_lua_ssl.c
- src/ngx_http_lua_ssl.h
- t/129-ssl-socket.t
* The *lua_ssl_key_log* directive is like [the ssl_key_log of Nginx](https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_key_log), but instead it logs client connection SSL keys in the [tcpsock:sslhandshake](https://github.com/openresty/lua-nginx-module?tab=readme-ov-file#tcpsocksslhandshake) method.
* Combining captured packets and key log file generated by this directive, it's good for us to debug encrypted traffic, like the following testing shows
* here using Wireshark to illustrate the usage of the key log file
* before using key log file
* after using key log file
> feature: lua_ssl_key_log directive
