src/ngx_http_lua_shdict.c

typo fix in debug log

---

src/ngx_http_lua_req_body.c
src/ngx_http_lua_variable.c

Hello,
Lintian[0] complains about spelling-error-in-binary errors.
[0] https://lintian.debian.org/tags/spelling-error-in-binary.html

Typo fixes

---

doc/HttpLuaModule.wiki

doc: sync the change from README.markdown to wiki

---

src/ngx_http_lua_module.c

change: we now print an alert when a non openresty-specific version of luajit is detected

---

src/ngx_http_lua_misc.c

Sister PR: https://github.com/openresty/lua-resty-core/pull/198

feature: added an FFI API for retrieving env configuration values.

---

README.markdown
doc/HttpLuaModule.wiki

doc: noted ngx.req.get_method also can be used in the body_filter_lua* phase and log_by_lua* phase

---

.gitignore
t/004-require.t
t/025-codecache.t
t/081-bytecode.t
t/109-timer-hup.t
t/134-worker-count-5.t
t/138-balancer.t
t/157-socket-keepalive-hup.t

To be rebased once #1414 is merged. We can now run this module's regular test suite in about just 4 minutes :)

 tests: updated the test suite so that it can be run in parallel mode. 

---

README.markdown
doc/HttpLuaModule.wiki

doc: updated the copyright year to 2019.

---

t/087-udp-socket.t
t/108-timer-safe.t
t/159-sa-restart.t

tests: hardened a few flaky test cases from recent CI runs.

---

.travis.yml
t/023-rewrite/client-abort.t
t/023-rewrite/tcp-socket-timeout.t
t/023-rewrite/tcp-socket.t
t/023-rewrite/uthread-exit.t
t/024-access/client-abort.t
t/024-access/uthread-exit.t
t/027-multi-capture.t
t/030-uri-args.t
t/058-tcp-socket.t
t/065-tcp-socket-timeout.t
t/068-socket-keepalive.t
t/090-log-socket-errors.t
t/094-uthread-exit.t
t/100-client-abort.t
t/127-uthread-kill.t
t/128-duplex-tcp-socket.t
t/147-tcp-socket-timeouts.t

tests: switched to 127.0.0.2 instead of agentzh.org for timeout-related tests.

---

t/023-rewrite/tcp-socket.t
t/023-rewrite/uthread-exit.t
t/024-access/uthread-exit.t
t/058-tcp-socket.t
t/094-uthread-exit.t
t/124-init-worker.t

tests: fixed failures due to recent CDN changes.

---

src/ngx_http_lua_pipe.c

bugfix: ngx.pipe: cleared the pending event after aborting the uthread.

---

src/ngx_http_lua_string.c

Sister PR for https://github.com/openresty/lua-resty-core/pull/247

feature: added the FFI API for 'str_replace_char()'.

---

src/ngx_http_lua_log.c

bugfix: LuaJIT sets currentline to -1 if it is unavailable.

---

.travis.yml
t/139-ssl-cert-by.t

Sister PRs:
- https://github.com/openresty/openresty/pull/503
- https://github.com/openresty/no-pool-nginx/pull/8
- https://github.com/openresty/stream-lua-nginx-module/pull/169

change: upgraded the NGINX core to 1.17.1

---

config

bugfix: config: fallback to '--undefined' option for ld 2.25 and below.

---

src/ngx_http_lua_pipe.c

As per the [ngx.pipe](https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/pipe.md#stderr_read_all) documentation:
If the reading operation is aborted by the shutdown method, it will return nil and the error string "aborted".
[...]
Reading from an exited process's stream will return nil and the error string "closed".
However, prior to this patch, a process that exits while reads are pending would make `std*_read_*()` calls return the "aborted" error, when they should have returned "closed".
This was caught by the `MOCKEAGAIN=r` testing mode:
t/pipe-stdout.t .. 1/18
Failed test 'TEST 28: read process while waiting process in other request - response_body - response is expected
@@ -1,3 +1,3 @@
-hello world
+aborted
exit
2
---
> I hereby granted the copyright of the changes in …

bugfix: ngx.pipe: ensured reading while a process died returns the "closed" error.

---

t/139-ssl-cert-by.t

tests: 139-ssl-cert-by.t: relaxed timing test cases for tvw test mode.

---

src/ngx_http_lua_initworkerby.c

I refer the style of [here](https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_initworkerby.c#L53), @thibaultcha could you help me check it? Thanks a lot.

style: unit style of nested define statement.

---

src/ngx_http_lua_socket_tcp.c

style: ensure there is two blank lines before functions

---

src/ngx_http_lua_logby.c

chore: remove duplicate headers in ngx_http_lua_logby.c

---

.travis.yml
t/000--init.t

fix: add lua-resty-string to lua_package_path

---

.travis.yml

test: use official repo instead of third pard repo

---

README.markdown

removes semicolon in lua codes in a document file.

remove semicolon in lua codes

---

README.markdown
doc/HttpLuaModule.wiki
t/045-ngx-var.t

ngx.var.VARIABLE is supported in balancer_by_lua context, add balancer_by_lua* to ngx.var.VARIABLE's doc.
Add balancer_by_lua test case to t/045-ngx-var.t.
#1731

doc: ngx.var.VARIABLE is available in the balancer_by_lua* context

---

src/ngx_http_lua_ctx.c

bugfix: added missing SSL feature macro

---

t/108-timer-safe.t

test: increased time unit to make test less error-prone

---

t/030-uri-args.t

test: there is no fixed order in lua table when call ngx.encode_args.

---

src/ngx_http_lua_accessby.c
src/ngx_http_lua_contentby.c
src/ngx_http_lua_coroutine.c
src/ngx_http_lua_module.c
src/ngx_http_lua_rewriteby.c
src/ngx_http_lua_ssl_certby.c
src/ngx_http_lua_ssl_session_fetchby.c
src/ngx_http_lua_timer.c
src/ngx_http_lua_uthread.c
src/ngx_http_lua_util.c
src/ngx_http_lua_util.h

Optimize: made co_ctx lookup an O(1) operation by using our LuaJIT's new exdata2 API

---

src/ngx_http_lua_sleep.c
src/ngx_http_lua_socket_tcp.c

Please see #1779 for more details.

bugfix: build error with nginx 1.7.4 or older version

---

t/163-signal.t

tests: skip t/163-signal.t under hup reload test mode.

---

src/ngx_http_lua_output.c
src/ngx_http_lua_util.c

bugfix: ngx.flush never blocks on http v2.

---

src/ngx_http_lua_subrequest.c

bugfix: wrong pipelined request body length when request body is parent's request body.

---

t/124-init-worker.t

tests: modified match pattern for TEST 22 'destroy Lua VM in cache processes.

---

src/ngx_http_lua_timer.c
t/106-timer.t

bugfix: used uninitialized value make nginx core when lua_getinfo return failed.

---

t/106-timer.t

tests: 106-timer.t: fixed test plan count.

---

t/030-uri-args.t
t/129-ssl-socket.t

docs: fix spelling

---

README.markdown
doc/HttpLuaModule.wiki

doc: recommend to renew ngx.timer.at regularly

---

valgrind.suppress

tests: added a new rule about 'ngx_pass_open_channel()' to valgrind suppression file.

---

t/160-disable-init-by-lua.t

tests: suspected memory leak when set TEST_NGINX_CHECK_LEAK=1 because forgot to close file in 160-disable-init-by-lua.t.

---

src/api/ngx_http_lua_api.h

bumped the API version to 0.10.20.

---

src/ngx_http_lua_pipe.c

feature: support environ in ngx.pipe on mac

---

src/ngx_http_lua_module.c
t/129-ssl-socket.t

bugfix: fixed typo introduced by 276f16af.

---

README.markdown
doc/HttpLuaModule.wiki

chore: fix typos introduced by PR #1890

---

src/ngx_http_lua_worker.c

add privileged agent connections argument in ngx_http_lua_ffi_enable_privileged_agent.

feature: add privileged agent connections.

---

src/ngx_http_lua_worker.c

bugfix: add nginx version condition for privileged connections.

---

.github/workflows/label.yml
.mergify.yml

feature: auto assign pr to project

---

src/ngx_http_lua_cache.c

bugfix: we should use luaL_typename() with lua stack index.

---

.travis.yml
src/ngx_http_lua_util.c
src/ngx_http_lua_util.h
t/166-worker-thread.t

doc: fixed code style and test case style found by ngx-releng.

---

src/ngx_http_lua_worker_thread.c
util/build.sh

bugfix: ngx_http_lua_assert failed in ngx_http_lua_worker_thread.c.

---

.travis.yml

travis-ci: updated ftp.pcre.org to sourceforge mirror for pcre download.

---

t/129-ssl-socket.t
t/162-exit-worker.t

tests: fixed test plan for 129-ssl-socket.t and 162-exit-worker.t.

---

src/ngx_http_lua_util.h

style: remove extra space.

---

src/ngx_http_lua_util.c

change: delete useless code of getting old_cpath

---

src/ngx_http_lua_directive.c
src/ngx_http_lua_exitworkerby.c
src/ngx_http_lua_initby.c
src/ngx_http_lua_initworkerby.c
t/041-header-filter.t
t/086-init-by.t
t/089-phase.t
t/091-coroutine.t
t/124-init-worker.t
t/162-exit-worker.t

bugfix: passing the wrong chunkname argument to luaL_loadbuffer.

---

.travis.yml
src/ngx_http_lua_socket_tcp.c
t/058-tcp-socket.t
t/071-idle-socket.t

bugfix: return 'close' error if pending_eof is set when set keepalive.

---

src/ngx_http_lua_initworkerby.c

bugfix: fixed size of the array when initialized in the init_worker_by* phase.

---

t/062-count.t

tests: change the count of the record after adding ngx.get_raw_phase.

---

.travis.yml
src/ngx_http_lua_bodyfilterby.c
src/ngx_http_lua_bodyfilterby.h
src/ngx_http_lua_setby.c
src/ngx_http_lua_setby.h
src/ngx_http_lua_util.c
t/062-count.t

feature: add FFI implementation for ngx.arg getter

---

README.markdown
doc/HttpLuaModule.wiki

doc: describe the second argument of get_uri_args

---

README.markdown
doc/HttpLuaModule.wiki

doc: did not generate README.markdown from doc/HttpLuaModule.wiki.

---

src/ngx_http_lua_common.h
src/ngx_http_lua_module.c

bugfix: failed to compile when nginx https is disabled.

---

.travis.yml
util/build-without-ssl.sh

ci: build-without-ssl

---

src/ngx_http_lua_headers.c
src/ngx_http_lua_headers_out.h
src/ngx_http_lua_shdict.c
src/ngx_http_lua_shdict.h

This is the workaround for luajit FFI working on apple silicon.
See:
https://github.com/openresty/lua-nginx-module/issues/2030
https://github.com/LuaJIT/LuaJIT/issues/205
Sister PR:
https://github.com/openresty/lua-resty-core/pull/391
https://github.com/openresty/stream-lua-nginx-module/pull/293

bugfix: Apple silicon workaround

---

src/ngx_http_lua_timer.c

doc: revised English grammar in ngx_http_lua_timer.c.

---

.travis.yml
src/ngx_http_lua_pipe.c
src/ngx_http_lua_pipe.h

optimize: destroy pipe proc when freeing the request.

---

src/ngx_http_lua_socket_udp.c
t/087-udp-socket.t

change: can not receive udp datagram greater 8192.

---

t/166-worker-thread.t

https://groups.google.com/g/openresty/c/qkS_9whMvXc

tests: change the running phase to cover the bug reported in google group.

---

.github/workflows/semantic-pull-request.yml

ci: add a way to check PR title automatically

---

.github/workflows/semantic-pull-request.yml

fix: update the PR types

---

config

bugfix: doesn't set flags for Darwin arm64.

---

README.markdown
src/ngx_http_lua_worker_thread.c
t/166-worker-thread.t

feature: add shdict APIs into worker thread

---

src/ngx_http_lua_uri.c

bugfix: typo in the debug message

---

README.markdown

doc: complete md5.lua example in run_worker_thread api

---

.travis.yml
util/build-with-dd.sh

tests: build with DDEBUG=1.

---

README.markdown
doc/HttpLuaModule.wiki

doc: fix the version in README

---

src/api/ngx_http_lua_api.h

Merge tag 0.10.22 into master.

---

README.markdown

doc: add release description for ngx.worker.pids().

---

src/ngx_http_lua_regex.c

style: add assertion to make linter happy

---

README.markdown
src/ngx_http_lua_time.c

The sister PR:  
https://github.com/openresty/lua-resty-core/pull/406
https://github.com/openresty/stream-lua-nginx-module/pull/302

feature: add new ffi api ngx_http_lua_ffi_monotonic_msec.

---

src/ngx_http_lua_bodyfilterby.c
src/ngx_http_lua_util.c
t/185-ngx-buf-double-free.t

bugfix: avoid buf double free in ngx.print if lua body filter enabled

---

README.markdown

doc: Add link to pre-defined Nginx variables

---

src/ngx_http_lua_socket_tcp.c
src/ngx_http_lua_socket_tcp.h
t/186-cosocket-busy-bufs.t

bugfix: define busy_bufs per cosocket

---

t/086-init-by.t
t/124-init-worker.t
t/162-exit-worker.t

For example:
TEST_NGINX_RANDOMIZE=1 prove -j8 -r -I. t/

tests: test failed when running in randomize mode.

---

src/ngx_http_lua_socket_tcp.c
t/066-socket-receiveuntil.t
t/084-inclusive-receiveuntil.t

bugfix: fix receiveuntil rest bytes count.

---

src/ngx_http_lua_headers.c

feature: added HTTP 3.0 support to ngx.req.http_version().

---

t/129-ssl-socket.t
t/162-socket-tls-handshake.t
t/186-cosocket-busy-bufs.t

tests: fixed some test cases in t/129-ssl-socket.t t/162-socket-tls-handshake.t t/186-cosocket-busy-bufs.t.

---

.travis.yml
src/ngx_http_lua_socket_tcp.c
t/014-bugs.t
util/nc_server.py

bugfix: cosocket did not exit when worker_shutdown_timeout handler is called.

---

src/api/ngx_http_lua_api.h

new: bumped the lua version to 0.10.23.

---

.travis.yml

tests: use the specified perl to execute cpanm.

---

README.markdown

doc: setoption is already available now

---

src/ngx_http_lua_headers.c
src/ngx_http_lua_shdict.c

bugfix: fixed warning of signed and unsigned.

---

README.markdown
src/ngx_http_lua_worker.c
t/122-worker-2.t
t/122-worker-3.t

bugfix: windows also need to support ngx_http_lua_ffi_worker_pids.

---

src/api/ngx_http_lua_api.h

pkg: bumped the lua version to 0.10.24.

---

src/ngx_http_lua_socket_tcp.c

style: error message typo fix

---

README.markdown
src/ngx_http_lua_accessby.c
src/ngx_http_lua_contentby.c
src/ngx_http_lua_req_body.c
src/ngx_http_lua_rewriteby.c
src/ngx_http_lua_server_rewriteby.c
t/023-rewrite/request_body.t
t/024-access/request_body.t
t/044-req-body.t

bugfix: disable http2 in body read due to http2 stream processing bug

---

src/ngx_http_lua_clfactory.c

style: comments typo correction and improvement

---

README.markdown

doc:modify args to the correct markdown format

---

src/ngx_http_lua_module.c

Analogous to https://hg.nginx.org/nginx/rev/9d98d524bd02

optimize: Optimized use of SSL contexts.

---

src/ngx_http_lua_accessby.c
src/ngx_http_lua_bodyfilterby.c
src/ngx_http_lua_common.h
src/ngx_http_lua_contentby.c
src/ngx_http_lua_directive.c
src/ngx_http_lua_headerfilterby.c
src/ngx_http_lua_rewriteby.c
src/ngx_http_lua_server_rewriteby.c
src/ngx_http_lua_socket_udp.c
src/ngx_http_lua_ssl_certby.c
src/ngx_http_lua_ssl_client_helloby.c
src/ngx_http_lua_ssl_session_fetchby.c
src/ngx_http_lua_timer.c
t/014-bugs.t

bugfix: use after free when encountering invalid http IF-Match header.

---

src/api/ngx_http_lua_api.h
src/ngx_http_lua_accessby.c
src/ngx_http_lua_bodyfilterby.c
src/ngx_http_lua_common.h
src/ngx_http_lua_contentby.c
src/ngx_http_lua_directive.c
src/ngx_http_lua_headerfilterby.c
src/ngx_http_lua_rewriteby.c
src/ngx_http_lua_server_rewriteby.c
src/ngx_http_lua_socket_udp.c
src/ngx_http_lua_ssl_certby.c
src/ngx_http_lua_ssl_client_helloby.c
src/ngx_http_lua_ssl_session_fetchby.c
src/ngx_http_lua_timer.c
t/014-bugs.t
t/166-ssl-client-hello.t

bumped version to 0.10.25.

---

README.markdown
src/ngx_http_lua_args.c
t/030-uri-args.t

feature: allow get empty key for ngx.req.get_uri().

---

README.markdown
doc/HttpLuaModule.wiki

doc: add README of lua_ssl_certificate and lua_ssl_certificate_key

---

.travis.yml
t/028-req-header.t
t/129-ssl-socket.t
t/142-ssl-session-store.t
t/162-socket-tls-handshake.t
util/build-with-dd.sh
util/build-without-ssl.sh
util/build.sh
util/ver-ge

https://github.com/openresty/openresty/pull/920

new: upgrade nginx core to 1.25.1

---

src/ngx_http_lua_headers_in.c

bugfix: fixed compilation error: variable 'nelts' set but not used.

---

README.markdown

doc: revise the description regarding Nginx compatibility.

---

README.markdown
doc/HttpLuaModule.wiki

doc: update release date

---

README.markdown

doc: update TODO list since tcpsock:bind is already implemented

---

.travis.yml

tests: check if the version number has been specified before downloading OpenSSL.

---

.travis.yml
t/066-socket-receiveuntil.t
t/082-body-filter.t
t/138-balancer-upstream-bind.t

bugfix: fix some failed test case

---

src/ngx_http_lua_socket_tcp.c

chore: more accurate error messages

---

src/ngx_http_lua_module.c
src/ngx_http_lua_ssl_client_helloby.c

comments: make some debug message and comments accurate

---

t/102-req-start-time.t
t/129-ssl-socket.t

tests: adjust some test cases for HTTP3.

---

README.markdown
doc/HttpLuaModule.wiki

doc: add http2 and http3 limitation doc comment for ngx.req.socket API

---

src/api/ngx_http_lua_api.h

bumped version to 0.10.26.

---

t/058-tcp-socket.t
t/128-duplex-tcp-socket.t

tests: t/128-duplex-tcp-socket: replacing constant port 7658 with a random port.

---

src/ngx_http_lua_common.h
src/ngx_http_lua_pcrefix.c
src/ngx_http_lua_pcrefix.h
src/ngx_http_lua_regex.c

optimize: Make the use of NGX_PCRE2 clearer

---

t/014-bugs.t
t/020-subrequest.t
t/045-ngx-var.t
t/093-uthread-spawn.t
t/106-timer.t
t/124-init-worker.t
t/129-ssl-socket.t
t/139-ssl-cert-by.t
t/163-exit-worker-hup.t
t/166-ssl-client-hello.t

tests: use random ports instead of constant ports to prevent conflicts during testing.

---

src/ngx_http_lua_balancer.c
t/138-balancer.t

rewrite PR: https://github.com/openresty/lua-nginx-module/pull/1687

feature: add FFI function for balancer.disable_ssl.

---

src/ngx_http_lua_util.c
t/020-subrequest.t

bugfix: fixed HTTP request smuggling in the HEAD request.

---

README.markdown
src/ngx_http_lua_socket_tcp.c
src/ngx_http_lua_socket_udp.c
src/ngx_http_lua_socket_udp.h
t/062-count.t
t/087-udp-socket.t

feature: add udp cosocket bind api

---

src/ngx_http_lua_socket_tcp.c
t/058-tcp-socket.t
t/083-bad-sock-self.t

feature: add support of sending cdata for the tcp socket.

---

src/ngx_http_lua_socket_tcp.c
t/068-socket-keepalive.t

bugfix: wrong arguments of setkeepalive() result in the compromise of data integrity.

---

README.markdown
src/ngx_http_lua_socket_tcp.c
src/ngx_http_lua_socket_tcp.h
src/ngx_http_lua_socket_udp.c
t/058-tcp-socket.t
t/062-count.t
t/067-req-socket.t
t/083-bad-sock-self.t
t/087-udp-socket.t
t/116-raw-req-socket.t

feature: add support for cdata pointer.
This is a following commit of 8e47108e486a8810.

feature: add support for sending cdata through cosocket.

---

README.markdown
src/ngx_http_lua_module.c
src/ngx_http_lua_worker_thread.c
t/166-worker-thread.t

bugfix: worker thread Lua VM may take lots of memory.

---

src/ngx_http_lua_initworkerby.c

I don't know how to write the unit test about the issues , sorry

bugfix: main thread access free fake request

---

README.markdown

fixes: update lua-cjson outdated ref link

---

src/api/ngx_http_lua_api.h

bumped version of lua-nginx-module to 10027.

---

src/ngx_http_lua_ssl_certby.c

chore: more accurate error message

---

src/ngx_http_lua_accessby.c

chore: add missing space

---

src/ngx_http_lua_ssl_client_helloby.c

https://github.com/openresty/lua-nginx-module/issues/2413
This is a prerequisite to implementing https://github.com/fooinha/nginx-ssl-ja3 in Lua
https://github.com/openresty/lua-resty-core/pull/496
Corresponding PR in lua-resty-core

feature: ngx_http_lua_ffi_ssl_get_client_hello_ext_present()

---

README.markdown

doc: update version info
